### ISSUE TITLE
add workflow pointers to other repo url-branch and import or checkout as required

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#132]
cross-repo workflows such as including ironSkillet with sdwan can become challenging since the workflow label can be release version specific and dependent on the currently checked out branch.

Running the workflow results in an error message that a skillet by cryptic label name is not found. Typical users would not know what this means or how to resolve.

Items to consider:
. create a meta-data label specifying the sourced skillet repo url and branch
. if repo is not imported then import and switch to the required branch
. if already imported then switch to the required branch

The issue seen is the user is unaware of what branch is required for a workflow (from the user view) and may not know to switch to another repo to checkout the proper branch. Looking for panHandler to assist the user with proper branch checkout.

Other obvious issue is reference a skillet repo not currently imported. without digging into the metadata file the user would not know what repo and branch to import.

**Comment by nembery** [comment]
Since workflows may have a hard dependency on other repos, this should be implemented as a top-level attribute in the skillet definition file. Recommendation would be a list of dicts like the following:

```yaml

depends:
  - url: https://github.com/paloaltonetworks/iron-skillet
    branch: panos_9.0
    name: IronSkilllet
  - url: https://github.com/paloaltonetworks/skillet-tools
    branch: panos_9.0
    name: SkilletTools

```

Short term goal is to issue a warning on import if these are NOT found currently installed and available in the local repository cache. Long term goal is to auto pull them.
