### ISSUE TITLE
Error with REST type skillet in panhandler

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/panhandler#154]
Issue appears to be adding a custom entry in the headers dict

```
snippets:
  - name: Retrieve Remote Network Service IP from Prisma Access
    path: xxx
    operation: GET
    headers:
      header-api-key: xxxx
```
