### ISSUE TITLE
Supported versions in .meta-cnc 

### ISSUE THREAD

**Issue by adambaumeister** [PaloAltoNetworks/panhandler#73]
It would be good to have the support panos versions embedded within each skillet metafile so utilities can determine whether the target system will support it. Ideally they should be regex.

```yaml
# snippet folder name
name: skillet_panos_v90
# label used for menu selection
label: v9.0 Iron-Skillet for NGFW
description: Iron-Skillet baseline configuration for a firewall
dependency: snippets_panorama
# type of device configuration
type: panos
# versions of PANOS this skillet supports.
supported_versions:
   - 9.0
   - 8.[0-1]
```
